services:
  frontend:
    restart: always
    build:
      context: frontend
      target: development
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    networks:
      - react-express
    expose:
      - 3000
    depends_on:
      - backend
  backend:
    restart: always
    build:
      context: backend
      target: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    # depends_on:
    #   - mongo
    ports:
      - 3001:3001
    expose:
      - 3001
    networks:
      - express-mongo
      - react-express
  # mongo:
  #   restart: always
  #   image: mongo
  #   volumes:
  #     - ./data:/data/db
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - express-mongo
  #   # expose:
  #   #   - 27017
networks:
  react-express:
  express-mongo:
