# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.1.53/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: Default page
  alias:
    - G97DVk1
  content:
    - component: Form
      name: planForm
      children:
        - component: PageRow
          name: days
          props:
            justifyContent: start
          children:
            - component: Select
              name: monday
              props:
                options:
                  $$jsExpression: mealsTable.rows.map(row => row.name)
                label: Monday
                name: Monday
            - component: Select
              name: tuesday
              props:
                options:
                  $$jsExpression: mealsTable.rows.map(row => row.name)
                label: Tuesday
                name: Tuesday
            - component: Select
              name: wednesday
              props:
                options:
                  $$jsExpression: mealsTable.rows.map(row => row.name)
                name: Wednesday
                label: Wednesday
            - component: Select
              name: thursday
              props:
                options:
                  $$jsExpression: mealsTable.rows.map(row => row.name)
                label: Thursday
                name: Thursday
            - component: Select
              name: friday
              props:
                options:
                  $$jsExpression: mealsTable.rows.map(row => row.name)
                label: Friday
                name: Friday
            - component: Select
              name: saturday
              props:
                options:
                  $$jsExpression: mealsTable.rows.map(row => row.name)
                label: Saturday
                name: Saturday
            - component: Select
              name: sunday
              props:
                options:
                  $$jsExpression: mealsTable.rows.map(row => row.name)
                label: Sunday
                name: Sunday
      props:
        hasResetButton: true
        formControlsFullWidth: false
        onSubmit:
          $$jsExpressionAction: savePlan.call()
    - component: DataGrid
      name: mealsTable
      props:
        rowsSource: prop
        dataProviderId: meals.ts:default
        rowIdField: name
        rows:
          $$jsExpression: >-
            getMeals.data.map(meal => {
              const portions = meal.portionIds.map(portionId => (
                portionsTable.rows.find(portion => portion.id === portionId)
              ))

              const portionsFormatted = portions.map(portion => `${portion.amount}${portion.unit || ""} ${portion.ingredient}`)

              return {
                ...meal,
                portions: portionsFormatted
              }
            })
        columns:
          - field: id
            type: number
          - field: name
            type: string
          - field: portions
            type: json
      layout:
        height: 360
    - component: DataGrid
      name: portionsTable
      props:
        rowsSource: prop
        dataProviderId: portions.ts:default
        rows:
          $$jsExpression: >-
            getPortions.data.map(portion => {
              const ingredient = ingredientsTable.rows.find(ingredient => ingredient.id === portion.ingredientId);

              return {
                ...portion,
                ingredient: ingredient.name,
                unit: ingredient.unit
              }
            })
        columns:
          - field: id
            type: number
          - field: ingredient
            type: string
            width: 150
          - field: amount
            type: number
          - field: unit
            type: string
        rowIdField: id
    - component: DataGrid
      name: ingredientsTable
      props:
        rowsSource: prop
        dataProviderId: ingredients.ts:default
        rows:
          $$jsExpression: getIngredients.data
        columns:
          - field: id
            type: number
          - field: name
            type: string
          - field: unit
            type: string
  queries:
    - name: getMeals
      mode: query
      query:
        function: functions.ts#getMeals
        kind: local
    - name: getIngredients
      mode: query
      query:
        function: functions.ts#getIngredients
        kind: local
    - name: getPortions
      mode: query
      query:
        function: functions.ts#getPortions
        kind: local
    - name: savePlan
      mode: mutation
      query:
        function: functions.ts#savePlan
        kind: local
      parameters:
        - name: plan
          value:
            $$jsExpression: |-
              (() => {
                let plan = {}

                Object.entries(planForm.value).forEach(([day, name]) => {
                  plan[day] = mealsTable.rows.find(row => row.name === name);
                });

                return plan;
              })()
