# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.1.53/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: Default page
  alias:
    - G97DVk1
  content:
    - component: DataGrid
      name: meals
      props:
        rowsSource: prop
        dataProviderId: meals.ts:default
        rowIdField: name
        rows:
          $$jsExpression: |-
            getMeals.data.map(meal => {
              const portions = meal.portionIds.map(portionId => (
                getPortions.data.find(portion => portion.id === portionId)
              ))

              return {
                ...meal,
                portions
              }
            })
        columns:
          - field: id
            type: number
          - field: name
            type: string
          - field: portions
            type: json
      layout:
        height: 360
    - component: DataGrid
      name: portions
      props:
        rowsSource: prop
        dataProviderId: portions.ts:default
        rowIdField: id
        rows:
          $$jsExpression: >-
            getPortions.data.map(portion => {
              const ingredient = getIngredients.data.find(ingredient => ingredient.id === portion.ingredientId);

              return {
                ...portion,
                ingredient,
              }
            })
        columns:
          - field: id
            type: number
          - field: ingredient
            type: json
            width: 150
          - field: amount
            type: number
    - component: DataGrid
      name: ingredients
      props:
        rowsSource: prop
        dataProviderId: ingredients.ts:default
        columns:
          - field: id
            type: string
          - field: name
            type: string
        rows:
          $$jsExpression: getIngredients.data
  queries:
    - name: getMeals
      mode: query
      query:
        function: functions.ts#getMeals
        kind: local
    - name: getIngredients
      mode: query
      query:
        function: functions.ts#getIngredients
        kind: local
    - name: getPortions
      mode: query
      query:
        function: functions.ts#getPortions
        kind: local
