# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.1.53/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: Default page
  alias:
    - G97DVk1
  content:
    - component: Form
      name: planForm
      children:
        - component: PageRow
          name: days
          props:
            justifyContent: start
          children:
            - component: Select
              name: monday
              props:
                options:
                  $$jsExpression: getMeals.data.records.map(row => row.name).sort()
                label: Monday
                name: Monday
                defaultValue:
                  $$jsExpression: getSelectedMeals.data.monday.name
            - component: Select
              name: tuesday
              props:
                options:
                  $$jsExpression: getMeals.data.records.map(row => row.name).sort()
                label: Tuesday
                name: Tuesday
                defaultValue:
                  $$jsExpression: getSelectedMeals.data.tuesday.name
            - component: Select
              name: wednesday
              props:
                options:
                  $$jsExpression: getMeals.data.records.map(row => row.name).sort()
                name: Wednesday
                label: Wednesday
                defaultValue:
                  $$jsExpression: getSelectedMeals.data.wednesday.name
            - component: Select
              name: thursday
              props:
                options:
                  $$jsExpression: getMeals.data.records.map(row => row.name).sort()
                label: Thursday
                name: Thursday
                defaultValue:
                  $$jsExpression: getSelectedMeals.data.thursday.name
            - component: Select
              name: friday
              props:
                options:
                  $$jsExpression: getMeals.data.records.map(row => row.name).sort()
                label: Friday
                name: Friday
                defaultValue:
                  $$jsExpression: getSelectedMeals.data.friday.name
            - component: Select
              name: saturday
              props:
                options:
                  $$jsExpression: getMeals.data.records.map(row => row.name).sort()
                label: Saturday
                name: Saturday
                defaultValue:
                  $$jsExpression: getSelectedMeals.data.saturday.name
            - component: Select
              name: sunday
              props:
                options:
                  $$jsExpression: getMeals.data.records.map(row => row.name).sort()
                label: Sunday
                name: Sunday
                defaultValue:
                  $$jsExpression: getSelectedMeals.data.sunday.name
      props:
        hasResetButton: true
        formControlsFullWidth: false
        onSubmit:
          $$jsExpressionAction: savePlan.call()
        submitButtonText: Save
    - component: DataGrid
      name: mealsTable
      props:
        rowsSource: dataProvider
        dataProviderId: meals.ts:default
        columns:
          - field: _id
            type: string
            width: 230
          - field: portionIds
            type: json
          - field: name
            type: string
          - field: portions
            type: json
        rowIdField: _id
    - component: DataGrid
      name: portionsTable
      props:
        rowsSource: dataProvider
        dataProviderId: portions.ts:default
        columns:
          - field: _id
            type: string
            width: 230
          - field: ingredientId
            type: string
          - field: amount
            type: number
          - field: unit
            type: string
          - field: ingredient
            type: string
        rowIdField: _id
    - component: DataGrid
      name: ingredientsTable
      props:
        rowsSource: dataProvider
        dataProviderId: ingredients.ts:default
        columns:
          - field: _id
            type: string
            width: 230
          - field: name
            type: string
          - field: unit
            type: string
        rowIdField: _id
  queries:
    - name: getMeals
      mode: query
      query:
        function: meals.ts#getMealRecords
        kind: local
    - name: savePlan
      mode: mutation
      query:
        function: functions.ts#savePlan
        kind: local
      parameters:
        - name: plan
          value:
            $$jsExpression: planForm.value
    - name: getSelectedMeals
      mode: query
      query:
        function: functions.ts#getSelectedMeals
        kind: local
      parameters:
        - name: _id
          value: 65a0b66b2905078fad3092e5
