# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.1.53/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: Default page
  alias:
    - G97DVk1
  content:
    - component: DataGrid
      name: mealsTable
      props:
        rowsSource: prop
        dataProviderId: meals.ts:default
        rowIdField: name
        rows:
          $$jsExpression: |-
            getMeals.data.map(meal => {
              const portions = meal.portionIds.map(portionId => (
                portionsTable.rows.find(portion => portion.id === portionId)
              ))

              const portionsFormatted = portions.map(portion => `${portion.amount}${portion.unit || ""} ${portion.ingredient}`)

              return {
                ...meal,
                portions: portionsFormatted
              }
            })
        columns:
          - field: id
            type: number
          - field: name
            type: string
          - field: portions
            type: json
      layout:
        height: 360
    - component: DataGrid
      name: portionsTable
      props:
        rowsSource: prop
        dataProviderId: portions.ts:default
        rowIdField: id
        rows:
          $$jsExpression: >-
            getPortions.data.map(portion => {
              const ingredient = ingredientsTable.rows.find(ingredient => ingredient.id === portion.ingredientId);

              return {
                ...portion,
                ingredient: ingredient.name,
                unit: ingredient.unit
              }
            })
        columns:
          - field: id
            type: number
          - field: ingredient
            type: string
            width: 150
          - field: amount
            type: number
          - field: unit
            type: string
    - component: DataGrid
      name: ingredientsTable
      props:
        rowsSource: prop
        dataProviderId: ingredients.ts:default
        rows:
          $$jsExpression: getIngredients.data
        columns:
          - field: id
            type: number
          - field: name
            type: string
          - field: unit
            type: string
  queries:
    - name: getMeals
      mode: query
      query:
        function: functions.ts#getMeals
        kind: local
    - name: getIngredients
      mode: query
      query:
        function: functions.ts#getIngredients
        kind: local
    - name: getPortions
      mode: query
      query:
        function: functions.ts#getPortions
        kind: local
